"""add education levels and marital statuses and its keys

Revision ID: 1df432f683a8
Revises: bc119685372f
Create Date: 2026-01-14 23:10:45.231118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1df432f683a8'
down_revision: Union[str, Sequence[str], None] = 'bc119685372f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('education_levels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('marital_statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('clients', sa.Column('education_level_id', sa.Integer(), nullable=True))
    op.add_column('clients', sa.Column('marital_status_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'clients', 'education_levels', ['education_level_id'], ['id'])
    op.create_foreign_key(None, 'clients', 'marital_statuses', ['marital_status_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'clients', type_='foreignkey')
    op.drop_constraint(None, 'clients', type_='foreignkey')
    op.drop_column('clients', 'marital_status_id')
    op.drop_column('clients', 'education_level_id')
    op.drop_table('marital_statuses')
    op.drop_table('education_levels')
    # ### end Alembic commands ###
