"""add jobs and client.job_id

Revision ID: bc119685372f
Revises: 94c953f30599
Create Date: 2026-01-14 22:24:52.615327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc119685372f'
down_revision: Union[str, Sequence[str], None] = '94c953f30599'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('salary', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('clients', sa.Column('job_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'clients', 'jobs', ['job_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'clients', type_='foreignkey')
    op.drop_column('clients', 'job_id')
    op.drop_table('jobs')
    # ### end Alembic commands ###
